ci: drop support arm64
Because I failed instance creation on CI as below.
Error: Failed instance creation: Failed creating instance record: Requested architecture isn't supported by this host